core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('clubs/', views.ClubList.as_view(), name='club_list'),
    path('clubs/add/', views.ClubCreate.as_view(), name='club_create'),
    path('clubs/<slug:club_slug>/', views.ClubDetail.as_view(), name='club_detail'),
    path('clubs/<slug:club_slug>/edit/', views.ClubUpdate.as_view(), name='club_update'),
    path('clubs/<slug:club_slug>/archers/add/', views.ClubArcherCreate.as_view(), name='club_archer_create'),
    path('clubs/<slug:club_slug>/archived/', views.ArchiveArcherList.as_view(), name='archive_archer_list'),
    path('counties/add/', views.CountyCreate.as_view(), name='county_create'),
    path('archer/add/', views.ArcherCreate.as_view(), name='archer_create'),
    path('archer/<int:pk>)/', views.ArcherDetail.as_view(), name='archer_detail'),
    path('archer/<int:pk>/edit/', views.ArcherUpdate.as_view(), name='archer_update'),
    path('archer/<int:pk>)/archive/', views.ArcherArchive.as_view(), name='archer_archive'),
]

entries/urls.py
from django.urls import path

from entries import views

urlpatterns = [
    path('', views.CompetitionList.as_view(), name='tournaments_list'),
    path('add/', views.CompetitionCreate.as_view(), name='competition_create'),
    path('<slug:slug>/', views.CompetitionDetail.as_view(), name='competition_detail'),
    path('<slug:slug>/edit/', views.CompetitionUpdate.as_view(), name='competition_update'),
    path('<slug:slug>/entries/', views.EntryList.as_view(), name='entry_list'),
    path('<slug:slug>/entries/batch/', views.BatchEntryStart.as_view(), name='batch_entry_start'),
    path('<slug:slug>/entries/search/', views.ArcherSearch.as_view(), name='archer_search'),
    path('<slug:slug>/entries/add/<int:archer_id>/', views.EntryAdd.as_view(), name='entry_add'),
    path('<slug:slug>/entries/edit/<int:entry_id>/', views.EntryUpdate.as_view(), name='entry_update'),
    path('<slug:slug>/entries/delete/<int:entry_id>/', views.EntryDelete.as_view(), name='entry_delete'),
    path('<slug:slug>/target-list/', views.TargetList.as_view(), name='target_list'),
    path('<slug:slug>/target-list/api/', views.TargetListApi.as_view(), name='target_list_api'),
    path('<slug:slug>/target-list/pdf/', views.TargetListPdf.as_view(), name='target_list_pdf'),
    path('<slug:slug>/target-list/lunch/', views.TargetListLunch.as_view()),
    path('<slug:slug>/score-sheets/', views.ScoreSheets.as_view(), name='score_sheets'),
    path('<slug:slug>/score-sheets/<int:round_id>/', views.ScoreSheetsPdf.as_view(), name='score_sheets_pdf'),
    path('<slug:slug>/score-sheets/session/<int:session_id>/', views.SessionScoreSheetsPdf.as_view(), name='session_score_sheets_pdf'),
    path('<slug:slug>/running-slips/<int:round_id>/', views.RunningSlipsPdf.as_view(), name='running_slips_pdf'),

    path('<slug:slug>/registration/', views.Registration.as_view(), name='registration'),
]

tamlynscore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from scores.urls import archer_urlpatterns

urlpatterns = [
    path('', include('core.urls')),
    path('leagues/', include('leagues.urls')),
    path('tournaments/', include('entries.urls')),
    path('tournaments/', include('scores.urls')),
    path('tournaments/', include('judging.urls')),
    path('tournaments/olympic/', include('olympic.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('scoring/', include(archer_urlpatterns)),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import json

from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from custom_user.models import AbstractEmailUser

DISTANCE_UNITS = (
    ('m', 'metres'),
    ('y', 'yards'),
)


SCORING_TYPES = (
    ('F', 'Five Zone Imperial'),
    ('T', 'AGB Indoor - Ten Zone, no Xs, with hits'),
    ('X', 'WA Outdoor - Ten Zone, with Xs, no hits'),
    ('I', 'WA Indoor - Ten Zone, no Xs, no hits'),
    ('E', 'Xs are 11 - Eleven Zone, no hits'),
    ('W', 'Worcester'),
    ('S', 'Score only (e.g. IFAA Indoor)'),
)


GENDER_CHOICES = (
    ('G', 'Men'),
    ('L', 'Women'),
)


NOVICE_CHOICES = (
    ('N', 'Novice'),
    ('E', 'Experienced'),
)


SIMPLE_AGE_CHOICES = (
    ('J', 'Junior'),
    ('S', 'Senior'),
)

AGB_AGE_CHOICES = (
    ('', 'Senior'),
    ('50+', '50+'),
    ('65+', '65+'),
    ('U21', 'U21'),
    ('U18', 'U18'),
    ('U16', 'U16'),
    ('U15', 'U15'),
    ('U14', 'U14'),
    ('U12', 'U12'),
    ('U10', 'U10'),
)

IFAA_DIVISIONS = (
    ('P', 'Professional'),
    ('C', 'Cub'),
    ('J', 'Junior'),
    ('YA', 'Young Adult'),
    ('A', 'Adult'),
    ('V', 'Veteran'),
    ('S', 'Senior'),
)


class User(AbstractEmailUser):
    name = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.name


class Subround(models.Model):
    arrows = models.PositiveIntegerField()
    distance = models.PositiveIntegerField()
    unit = models.CharField(max_length=1, choices=DISTANCE_UNITS)
    target_face = models.PositiveIntegerField()

    def __str__(self):
        return '{0} arrows at {1} {2} ({3}cm)'.format(
            self.arrows,
            self.distance,
            self.get_unit_display(),
            self.target_face,
        )

    @property
    def distance_short(self):
        return '{}{}'.format(self.distance, self.unit)

    class Meta:
        ordering = ('unit', '-distance', '-arrows', '-target_face')


class Round(models.Model):
    name = models.CharField(max_length=100, unique=True)
    subrounds = models.ManyToManyField(Subround)
    longest_distance = models.IntegerField(default=0)  # Used for ordering results
    scoring_type = models.CharField(max_length=1, choices=SCORING_TYPES)
    can_split = models.BooleanField(
        default=False, help_text=(
            'If the round does not have multiple subrounds, but it makes sense '
            'to talk about two halves of the round (e.g. a WA18m or WA70m), then '
            'tick this box and the split can be used in exports.'
        ),
    )
    is_ifaa = models.BooleanField(default=False)
    # This is such a weird round we may as well special case it
    flint_round = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @property
    def arrows(self):
        return self.subrounds.aggregate(models.Sum('arrows'))['arrows__sum']

    def get_subround(self, doz_no):
        arrows = int(doz_no) * 12
        subrounds = self.subrounds.order_by('-distance')
        for subround in subrounds:
            if subround.arrows >= arrows:
                return subround
        raise Exception('There aren\'t that many dozens in that round!')

    @property
    def splits(self):
        if self.can_split:
            subround = self.subrounds.first()  # There should only be one anyway
            return [{
                'name': '%s-1' % subround.distance_short,
                'arrows': subround.arrows / 2,
            }, {
                'name': '%s-2' % subround.distance_short,
                'arrows': subround.arrows / 2,
            }]
        else:
            return [{
                'name': subround.distance_short,
                'arrows': subround.arrows,
            } for subround in self.subrounds.order_by('-distance')]

    @property
    def has_xs(self):
        return self.scoring_type == 'X'

    @property
    def has_golds(self):
        return not self.is_ifaa

    @property
    def has_elevens(self):
        return self.scoring_type == 'E'

    @property
    def gold_9s(self):
        return self.scoring_type == 'F'

    @property
    def has_hits(self):
        if self.scoring_type in ['X', 'I', 'E']:
            return False
        if self.is_ifaa:
            return False
        return True

    @property
    def score_sheet_headings(self):
        if self.scoring_type == 'X':
            return ['10+X', 'X']
        if self.scoring_type == 'E':
            return ['11s', '10s']
        elif self.scoring_type == 'I':
            return ['10s']
        elif self.is_ifaa:
            return []
        else:
            return ['H', 'G']

    @property
    def scoring_headings(self):
        if self.scoring_type == 'X':
            return ['10s+Xs', 'Xs']
        if self.scoring_type == 'E':
            return ['11s', '10s']
        elif self.scoring_type == 'I':
            return ['10s']
        else:
            return ['Hits', 'Golds']


class Bowstyle(models.Model):
    name = models.CharField(max_length=50, unique=True)
    ifaa_only = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = 'countries'

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(max_length=50, unique=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class County(models.Model):
    name = models.CharField(max_length=500, unique=True)
    short_name = models.CharField(max_length=50, unique=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'counties'
        ordering = ('short_name',)

    def __str__(self):
        return self.short_name


class Club(models.Model):
    name = models.CharField(max_length=500, unique=True)
    short_name = models.CharField(max_length=50, unique=True)

    county = models.ForeignKey(County, blank=True, null=True, on_delete=models.CASCADE)

    slug = models.SlugField(editable=False, unique=True)

    class Meta:
        ordering = ('short_name',)

    def clean(self, *args, **kwargs):
        self.slug = slugify(self.short_name)
        return super(Club, self).clean(*args, **kwargs)

    def __str__(self):
        return self.short_name

    def json(self):
        return json.dumps({
            'id': self.pk,
            'name': self.name,
            'short_name': self.short_name,
        })

    def get_absolute_url(self):
        return reverse('club_detail', kwargs={'club_slug': self.slug})


class Archer(models.Model):
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    club = models.ForeignKey(Club, blank=True, null=True, on_delete=models.CASCADE)
    bowstyle = models.ForeignKey(Bowstyle, on_delete=models.CASCADE)
    age = models.CharField(max_length=1, choices=SIMPLE_AGE_CHOICES, default='S')
    agb_age = models.CharField(max_length=3, choices=AGB_AGE_CHOICES, default='', blank=True)
    novice = models.CharField(max_length=1, choices=NOVICE_CHOICES, default='E')
    agb_number = models.BigIntegerField(blank=True, null=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def json(self):
        return json.dumps({
            'id': self.pk,
            'name': self.name,
            'age': self.age,
            'agb_age': self.agb_age,
            'gender': self.gender,
            'club': self.club.pk,
            'bowstyle': self.bowstyle.pk,
            'novice': self.novice,
            'agb_number': self.agb_number,
        })

    def merge_into(self, other):
        self.competitionentry_set.update(archer=other)
        self.delete()

entries/templates/entries/archer_search.html
{% extends 'entries/competition_detail.html' %}

{% block scripts %}
<script src="{{ STATIC_URL }}lib/jquery/jquery-2.1.3.min.js"></script>
{% endblock %}

{% block competition_content %}
<h2>Select archer to enter</h2>

{% if batch %}
<div class="batch-status">
    <p>Current row: <strong>{{ current_row }}</strong>. Rows to process: <strong>{{ batch_length }}</strong>.</p>
</div>
{% endif %}

<p>Enter an archer name:</p>
<form method="GET" action="{{ request.get_full_path }}">
    {{ search_form.query }}
    <input type="submit" class="btn" value="Search">
</form>

<p><a href="{% url 'archer_create' %}?competition={{ competition.slug }}{% if search_form.cleaned_data.query %}&name={{ search_form.cleaned_data.query|urlencode }}{% endif %}" class="btn">Create new archer</a></p>

{% if archers %}
<div class="row flex">
    {% for archer in archers %}
    <div class="col2">
        <a href="{% url 'entry_add' slug=competition.slug archer_id=archer.pk %}">
            <div class="archer-block">
                <div class="name">
                    <span>{{ archer }}</span>
                </div>
                <div class="bottom">
                    <p>
                        {{ archer.club }}
                    </p>
                    <p>
                        <span class="pill bowstyle {{ archer.bowstyle|slugify }}">{{ archer.bowstyle }}</span>
                        <span class="pill gender {{ archer.get_gender_display|lower }}">{{ archer.get_gender_display }}</span>
                        {% if competition.has_novices and archer.novice == "N" %}
                        <span class="pill novice">{{ archer.get_novice_display }}</span>
                        {% endif %}
                        {% if competition.has_juniors and archer.age == "J" %}
                        <span class="pill junior">{{ archer.get_age_display }}</span>
                        {% endif %}
                    </p>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% else %}
No archers found.
{% endif %}
{% endblock %}

entries/templates/entries/batch_entry_start.html
{% extends 'entries/competition_detail.html' %}

{% block competition_content %}
<form action="{{ request.get_full_path }}" method="post" class="page-form">
    {% csrf_token %}

	<div class="form-group">
		<h2>Add a batch of entries</h2>
        <div class="form-row">
            {{ form.data.as_field_group }}
        </div>
        <input type="submit" class="btn" />
	</div>
</form>
{% endblock %}

entries/templates/entries/competition_list.html
{% extends 'base.html' %}

{% block content %}
<header>
    {% if user.is_superuser %}
    <a class="pull-right btn add" href="{% url 'competition_create' %}">New tournament</a>
    {% endif %}
    <h1>Competitions</h1>
</header>

{% if current %}
<div class="row">
    <div class="col6">
        <h3>Competitions in progress</h3>
        <ul class="link-list">
            {% for competition in current %}
            <li>
                <a href="{% url 'competition_detail' slug=competition.slug %}">
                    {{ competition }}
                    <small>{{ competition.date|date:"jS F" }}</small>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endif %}

<div class="row">
    <div class="col3">
        <h3>Upcoming competitions</h3>
        <ul class="link-list">
            {% for competition in upcoming %}
            <li>
                <a href="{% url 'competition_detail' slug=competition.slug %}">
                    {{ competition }}
                    <small>{{ competition.date|date:"jS F" }}</small>
                </a>
            </li>
            {% empty %}
            <li>
                <p>No upcoming competitions.</p>
            </li>
            {% endfor %}
        </ul>
    </div>

    {% if past %}
    <div class="col3">
        <h3>Completed competitions</h3>
        {% for competition in past %}
            {% ifchanged competition.date.year %}
                {% if not forloop.first %}
                </ul>
                </div>
                {% endif %}
                <div class="year-accordion {% if forloop.first %}year-accordion--active{% endif %}">
                    <h4 class="year-accordion__header">{{ competition.date.year }}</h4>
            <ul class="link-list">
            {% endifchanged %}
                <li>
                <a href="{% url 'competition_detail' slug=competition.slug %}">
                    {{ competition }}
                    <small>{{ competition.date|date:"jS F" }}</small>
                </a>
                </li>
        {% endfor %}
        </ul>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}


{% block scripts %}
<script>
    document.querySelectorAll('.year-accordion').forEach(function(el) {
        var header = el.querySelector('.year-accordion__header');
        header.addEventListener('click', function() {
            el.classList.toggle('year-accordion--active');
        });
    });
</script>
{% endblock %}

entries/templates/entries/entry_add.html
{% extends 'entries/competition_detail.html' %}

{% block scripts %}
<script src="{{ STATIC_URL }}lib/jquery/jquery-2.1.3.min.js"></script>
{% endblock %}

{% block competition_content %}
<p>
    {% if competition.use_county_teams %}
        <a class="btn add pull-right" href="{% url 'county_create' %}?next={{ request.path }}">Add county</a>
    {% elif not competition.ifaa_rules %}
        <a class="btn add pull-right" href="{% url 'club_create' %}?next={{ request.path }}">Add club</a>
    {% endif %}
</p>
{% with archer|stringformat:"s" as title_suffix %}
    {% include "entries/entry_form_layout.html" with form_title="Create entry for "|add:title_suffix %}
{% endwith %}
{% endblock %}

entries/templates/entries/entry_delete.html
{% extends 'entries/competition_detail.html' %}

{% block competition_content %}
    <form action="{{ request.get_full_path }}" method="post">
        {% csrf_token %}
        <h2>Confirm deleting entry for {{ object }}</h2>
        {{ form }}
    <p><input type="submit" class="btn delete" value="Delete"></p>
{% endblock %}

entries/templates/entries/entry_list.html
{% extends 'entries/competition_detail.html' %}

{% block page_id %}entry-list{% endblock %}

{% block scripts %}
<script src="{{ STATIC_URL }}lib/jquery/jquery-2.1.3.min.js"></script>
{% endblock %}

{% block competition_content %}
<div class="row">
    <div class="col2">
        <form action="{% url 'archer_search' slug=competition.slug %}" method="GET">
            {{ search_form.query }}
            <button type="submit" class="btn add">Add entry</button>
        </form>
    </div>
    <div class="col4">
        <h3>Stats</h3>
        <div class="row row--flex">
            {% for session in stats %}
            <div class="col2">
            <strong>{{ session.session.start }}</strong><br>
            <span class="pill">{{ session.total_entries }} entr{{ session.total_entries|pluralize:"y,ies" }}</span><br>
            {% for sr in session.session_rounds %}
                {{ sr.session_round.shot_round }} <span class="pill">{{ sr.total_entries }} entr{{ sr.total_entries|pluralize:"y,ies" }}</span><br>
                {% if sr.total_entries %}
                    {% for bowstyle, count in sr.bowstyles %}
                    <span class="pill {{ bowstyle|slugify }}">{{ count }} {{ bowstyle }}</span>
                    {% if forloop.last %}<br>{% endif %}
                    {% endfor %}
                    {% if sr.junior_count %}
                    <span class="pill junior">{{ sr.junior_count }} Junior</span><br>
                    {% endif %}
                    {% if sr.agb_age_groups %}
                        {% for age_group, count in sr.agb_age_groups %}
                        <span class="pill {{ age_group|slugify }}">{{ count }} {{ age_group }}</span>
                        {% if forloop.last %}<br>{% endif %}
                        {% endfor %}
                    {% endif %}
                    {% for gender, count in sr.genders %}
                        <span class="pill {{ gender|slugify }}">{{ count }} {{ gender }}</span>
                        {% if forloop.last %}<br>{% endif %}
                    {% endfor %}
                    {% if sr.novice_count %}
                        <span class="pill novice">{{ sr.novice_count }} Novice</span><br>
                    {% endif %}
                    {% if sr.ifaa_division %}
                        {% for age_group, count in sr.ifaa_division %}
                        <span class="pill {{ age_group|slugify }}">{{ count }} {{ age_group }}</span>
                        {% if forloop.last %}<br>{% endif %}
                        {% endfor %}
                    {% endif %}
                {% endif %}
            {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="row">
    <div class="col6">
        <h3>Existing entries</h3>

        <div class="row flex">
        {% for entry in object_list %}
        <div class="col2">
            <div class="archer-block">
                <div class="name">
                    <div class="actions">
                        <a class="action-button edit" href="{% url 'entry_update' slug=competition.slug entry_id=entry.pk %}"></a>
                        <a class="action-button delete" href="{% url 'entry_delete' slug=competition.slug entry_id=entry.pk %}"></a>
                    </div>
                    <span>{{ entry.archer }}</span>
                </div>
                <div class="bottom">
                    <p>
                        {{ entry.team_name }}
                    </p>
                    {% for session in entry.sessionentry_set.all %}
                    <p>{{ session.session_round.session.start|date:"j/n fa" }} - {{ session.session_round.shot_round }}</p>
                    {% endfor %}
                    <p>
                        {% if competition.has_novices and entry.novice == "N" %}
                        <span class="pill novice">{{ entry.get_novice_display }}</span>
                        {% endif %}
                        <span class="pill bowstyle {{ entry.bowstyle|slugify }}">{{ entry.bowstyle }}</span>
                        {% if competition.has_juniors and entry.age == "J" %}
                        <span class="pill junior">{{ entry.get_age_display }}</span>
                        {% endif %}
                        {% if competition.has_agb_age_groups and entry.agb_age %}
                        <span class="pill junior">{{ entry.get_agb_age_display }}</span>
                        {% endif %}
                        <span class="pill gender {{ entry.archer.get_gender_display|lower }}">{{ entry.get_gender_display }}</span>
                        {% if entry.archer.agb_number %}
                            {{ entry.archer.agb_number }}
                        {% else %}
                            <strong>No AGB number</strong>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

entries/templates/entries/entry_update.html
{% extends 'entries/competition_detail.html' %}

{% block scripts %}
<script src="{{ STATIC_URL }}lib/jquery/jquery-2.1.3.min.js"></script>
{% endblock %}

{% block competition_content %}
<p>
    <a class="pull-right btn add" href="{% url 'club_create' %}?next={{ request.path }}">Add club</a>
</p>
{% with object.archer|stringformat:"s" as title_suffix %}
    {% include "entries/entry_form_layout.html" with form_title="Update entry for "|add:title_suffix %}
{% endwith %}
{% endblock %}

entries/templates/entries/registration.html
{% extends 'entries/competition_detail.html' %}

{% load qr_code %}

{% block scripts %}
<script src="{{ STATIC_URL }}lib/jquery/jquery-2.1.3.min.js"></script>
<script src="{{ STATIC_URL }}js/ajax-csrf.js"></script>
<script src="{{ STATIC_URL }}js/registration.js"></script>
{% endblock scripts %}

{% block competition_content %}
<div class="registration module">
    <h2>Registration</h2>

<div class="row">
    <div class="col6">
        <em>Sessions:</em>
        <ul>
            {% for session, details in target_list.items %}
            <li><p>
            <span>{{ session.start|date:"l, jS F - f a" }}</span>
            {% if details.entries|length %}
            <span class="unallocated" title="Unallocated entries">{{ details.entries|length }}</span>
            {% endif %}
            <a class="btn btn-small" href="#session-{{ session.pk }}">Skip</a>
            <small title="Unregistered entries">{{ details.unregistered }} unregistered</small>
            </p></li>
            {% endfor %}
        </ul>
    </div>
</div>

{% for session, details in target_list.items %}
<div class="row">
    <div class="col6">
        <div class="registration-board" id="session-{{ session.pk }}" rel="{{ session.archers_per_target }}">
            <div class="actions">
                <select class="club-filter">
                    <option data-club="--all--">--All--</option>
                </select>
            </div>
            <table class="table">
                <thead>
                    <th>Target</th>
                    <th>Name</th>
                    <th>{% if competition.use_county_teams %}County{% else %}Club{% endif %}</th>
                    <th>Bowstyle</th>
                    <th>Gender</th>
                    {% if competition.has_novices %}
                    <th>Experience</th>
                    {% endif %}
                    {% if competition.has_juniors %}
                    <th>Age</th>
                    {% endif %}
                    {% if competition.ifaa_rules %}
                    <th>Division</th>
                    {% endif %}
                    <th>{% if competition.ifaa_rules %}ID{% else %}ArcheryGB Number{% endif %}</th>
                    <th>Present</th>
                </thead>
                {% for boss, archers in details.target_list %}
                {% for target, archer in archers %}
                {% with archer.session_entry.competition_entry as entry %}
                <tr class="archer {% if not archer or archer.session_entry.present %}present{% endif %}" data-club="{% if competition.use_county_teams %}{{ entry.county_id }}{% else %}{{ entry.club_id }}{% endif %}" data-clubname="{% if competition.use_county_teams %}{{ archer.session_entry.competition_entry.county }}{% else %}{{ archer.session_entry.competition_entry.club }}{% endif %}">
                    <td>{{ boss }}{{ target }}</td>
                    <td>{% if archer %}<a href="{% url 'archer_update' pk=entry.archer_id %}?next={{ request.path }}">{{ entry.archer }}</a>{% endif %}</td>
                    <td>
                        {{ entry.team_name }}
                        {% if not competition.use_county_teams %}
                            {% if not entry.club == entry.archer.club %}
                            <span class="archer-details">({{ entry.archer.club.name }})</span>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td>
                        {% if archer %}
                            <span class="pill {{ entry.bowstyle|slugify }}">{{ entry.bowstyle }}</span>
                            {% if not entry.bowstyle == entry.archer.bowstyle %}
                            <span class="archer-details">(
                                <span class="pill {{ entry.archer.bowstyle|slugify }}">{{ entry.archer.bowstyle }}</span>
                            )</span>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td>
                        {% if archer %}
                            <span class="pill {{ entry.archer.get_gender_display|slugify }}">
                                {{ entry.get_gender_display }}
                            </span>
                        {% endif %}
                    </td>
                    {% if competition.has_novices %}
                    <td>
                        {% if archer and entry.novice == "N" or entry.archer.novice == "N" %}
                        <span class="pill novice">{{ entry.get_novice_display }}</span>
                        {% if not entry.get_novice_display == entry.archer.get_novice_display %}
                        <span class="archer-details">(
                            <span class="pill novice">{{ entry.archer.get_novice_display }}</span>
                        )</span>
                        {% endif %}
                        {% endif %}
                    </td>
                    {% endif %}
                    {% if competition.has_juniors %}
                    <td>{{ entry.get_age_display }}</td>
                    {% endif %}
                    {% if competition.ifaa_rules %}
                    <td>{{ entry.get_ifaa_division_display }}</td>
                    {% endif %}
                    <td>{{ entry.archer.agb_number }}</td>
                    <td>
                        {% if archer %}
                        <a href="#present" class="present btn" data-pk="{{ archer.session_entry.pk }}">Register</a>
                        <a href="#not-present" class="not-present btn" data-pk="{{ archer.session_entry.pk }}">Unregister</a>
                        {% endif %}
                    </td>
                    {% if session.device_scoring %}
                    <td>
                        {% if archer %}
                        <a href="{{ archer.login_url }}">
                            {% qr_from_text archer.login_url size="S" %}
                        </a>
                        {% endif %}
                    </td>
                    {% endif %}
                </tr>
                {% endwith %}
                {% endfor %}
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endfor %}

</div>

{% endblock %}

entries/templates/entries/target_list_react.html
{% extends 'entries/competition_detail.html' %}

{% load render_bundle from webpack_loader %}

{% block scripts %}
{% render_bundle 'target_list' 'js' %}
{% endblock %}

{% block competition_content %}
<div class="{% block moduleclass %}target-list{% endblock %} module">
    <div id="app" data-api-url="{% url "target_list_api" slug=competition.slug %}">Loading...</div>
</div>
{% endblock %}